authors:
  Aviel:
    name: Aviel Makmal
    description: Data Science
    avatar: https://avatars.githubusercontent.com/AvielMak
    slug: https://www.linkedin.com/in/avielmakmal/
    url: https://www.linkedin.com/in/avielmakmal/